// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwuoslxofjjvztwauwzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3dW9zbHhvZmpqdnp0d2F1d3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NjczNDIsImV4cCI6MjA2MTU0MzM0Mn0.YkXYn97az7iQiSRzNsvcZAzjI0EcFYINZpvI2TgF6dY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);